easy:
  - 'AMETHYST_BLOCK'
  - 'REDSTONE_BLOCK'
  - 'LAPIS_BLOCK'
  - 'EMERALD_BLOCK'
normal:
  - 'REDSTONE_BLOCK'
  - 'LAPIS_BLOCK'
  - 'EMERALD_BLOCK'
  - 'AMETHYST_BLOCK'
  - 'NETHERITE_BLOCK'
hard:
  - 'QUARTZ_BLOCK'
  - 'REDSTONE_BLOCK'
  - 'LAPIS_BLOCK'
  - 'EMERALD_BLOCK'
  - 'AMETHYST_BLOCK'
  - 'NETHERITE_BLOCK'