easy:
  - 'GOLD_BLOCK'
  - 'REDSTONE_BLOCK'
  - 'LAPIS_BLOCK'
  - 'EMERALD_BLOCK'
normal:
  - 'GOLD_BLOCK'
  - 'REDSTONE_BLOCK'
  - 'LAPIS_BLOCK'
  - 'QUARTZ_BLOCK'
  - 'NETHERITE_BLOCK'
hard:
  - 'GOLD_BLOCK'
  - 'REDSTONE_BLOCK'
  - 'LAPIS_BLOCK'
  - 'QUARTZ_BLOCK'
  - 'NETHERITE_BLOCK'
  - 'DIAMOND_BLOCK'