easy:
  - 'AMETHYST_BLOCK'
  - 'REDSTONE_BLOCK'
  - 'LAPIS_BLOCK'
  - 'EMERALD_BLOCK'
normal:
  - 'REDSTONE_BLOCK'
  - 'LAPIS_BLOCK'
  - 'EMERALD_BLOCK'
  - 'AMETHYST_BLOCK'
  - 'NETHERITE_BLOCK'
hard:
  - 'QUARTZ_BLOCK'
  - 'REDSTONE_BLOCK'
  - 'LAPIS_BLOCK'
  - 'EMERALD_BLOCK'
  - 'AMETHYST_BLOCK'
  - 'NETHERITE_BLOCK'
log:
  - 'OAK_LOG'
  - 'SPRUCE_LOG'
  - 'BIRCH_LOG'
  - 'JUNGLE_LOG'
  - 'ACACIA_LOG'
  - 'DARK_OAK_LOG'
leaves:
  - 'OAK_LEAVES'
  - 'SPRUCE_LEAVES'
  - 'BIRCH_LEAVES'
  - 'JUNGLE_LEAVES'
  - 'ACACIA_LEAVES'
  - 'DARK_OAK_LEAVES'